server:
  port: 8080

spring:
  application:
    name: "mini_projet"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
